FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ARG NUM_THREADS=4
ENV TZ=Europe/Rome

# Timezone
RUN apt-get update && \
    apt-get install -y tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# Toolchain + deps
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    curl \
    unzip \
    libgl1 \
    libx11-6 \
    libxi6 \
    libxxf86vm1 \
    libxrender1 \
    libxrandr2 \
    libxinerama1 \
    libxcursor1 \
    libboost-all-dev \
    python3 \
    python3-pip \
    ca-certificates \
    libglu1-mesa

RUN apt-get update && apt-get install -y \
    libx11-dev \
    libxext-dev \
    libxrandr-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxi-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev

# Install PMP
WORKDIR /opt
RUN git clone https://github.com/pmp-library/pmp-library.git
WORKDIR /opt/pmp-library
RUN mkdir build && cd build && cmake .. && make -j${NUM_THREADS} && make install

# Install Blender 4.4 (Release or Alpha)
WORKDIR /opt
ENV BLENDER_VERSION=4.4.0
RUN wget https://download.blender.org/release/Blender4.4/blender-${BLENDER_VERSION}-linux-x64.tar.xz && \
    tar -xf blender-${BLENDER_VERSION}-linux-x64.tar.xz && \
    ln -s /opt/blender-${BLENDER_VERSION}-linux-x64/blender /usr/local/bin/blender && \
    rm blender-${BLENDER_VERSION}-linux-x64.tar.xz

RUN apt-get update && \
    apt install -y libxkbcommon0 libsm6 libxrender1 libxext6 libxi6

RUN apt install -y libeigen3-dev

# Install CGAL 6.0.1
WORKDIR /opt
RUN wget https://github.com/CGAL/cgal/releases/download/v6.0.1/CGAL-6.0.1.tar.xz && \
    tar -xf CGAL-6.0.1.tar.xz && \
    mkdir CGAL-6.0.1/build && \
    cd CGAL-6.0.1/build && \
    cmake .. && \
    make -j8 && \
    make install

RUN apt-get install -y libtbb-dev libgmp-dev libmpfr-dev liblapack-dev libblas-dev

RUN mkdir -p /opt/nanoflann/include
RUN git clone https://github.com/jlblancoc/nanoflann.git /tmp/nanoflann && \
    cp /tmp/nanoflann/include/nanoflann.hpp /opt/nanoflann/include/ && \
    rm -rf /tmp/nanoflann

# Optional: Python deps inside Blender (e.g. numpy)
RUN /opt/blender-4.4.0-linux-x64/4.4/python/bin/python3.11 -m pip install trimesh xatlas scipy opencv-python

RUN pip install pyyaml

# Cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Default workdir
WORKDIR /workspace

COPY ./main.py .
COPY ./python/*.py ./python/
COPY ./c++/source/build/remesh /opt/

# ENTRYPOINT ["python3", "main.py"]