pipeline:
  input_folder: "/data/data/test_2/"
  output_dir: "/data/data/test_2/"
  image_resolution: 2048
  quality: "medium"
  skip_remesh: true  # Set to true to skip the CGAL remeshing step
  decimation:
    hausdorff_threshold: 0.001 # Max deviation for final decimation
  remesh:
    tolerance: 0.001
    edge_min: null    # auto: 0.1% of bbox diagonal
    edge_max: null    # auto: 5% of bbox diagonal
    iterations: 5
